### ISSUE TITLE
Won't let me log in

### ISSUE THREAD

**Issue by TheWaouh** [meower-media-co/Meower#77]
I tried logging in under my Scratch username, and got stuck in the "Please wait..." screen. My username isn't inappropriate. Does this have to do with #68?

**Comment by MikeDev101** [comment]
Last time I checked we didn't push a new build. If it's taking longer than 15 seconds to bring up the authentication screen you might need to refresh the page. Typically it will take around 15-ish seconds for CloudDisk to get ready. (The storage drives Meower uses need some time to spin up).

**Comment by tnix100** [comment]
I have this problem as well, even refreshing hasn't helped.

**Comment by MikeDev101** [comment]
CloudAccount needed to be refreshed. Server should be working now.

**Comment by tnix100** [comment]
Sadly still not working. I've tried clearing cache, using incognito, etc.

**Comment by Bloctans** [comment]
green flag 1: frezzes upon entering use name
green flag 2: oops cant connect
green flag 3 and so on: Connecting.... no sound effects.

**Comment by MikeDev101** [comment]
Server reboot in progress.

**Comment by tnix100** [comment]
https://scratch.mit.edu/discuss/post/5819260/
Look at EDIT2 on my post.

**Comment by MikeDev101** [comment]
Please join our discord so I can help figure out this error in real-time. https://discord.gg/E3anJj7PWX

**Comment by MikeDev101** [comment]
closing, gone stale and will be fixed in next build
